### ISSUE TITLE
Truncated pop-up in the Details view

### ISSUE THREAD

**Issue by rene-coty** [mrvladus/Errands#153]
The calendar pop-up in the Details view isn't scrollable and part of its content is masked when the screen size isn't super big and the pop-up is cut off (see screenshot below, on the bottom right corner)

![Capture d’écran du 2024-01-11 18-48-19](https://github.com/mrvladus/Errands/assets/95506494/1dff815a-85b5-4426-985c-4414db3ffc3a)

Would it be possible to make its content scrollable?

**Comment by mrvladus** [comment]
Fixed in 4a2fad916fac0584131a468a2559cf456433b4d5. Will be in the next release. Thank you!

**Comment by mrvladus** [comment]
Fixed in [45.1.6](https://github.com/mrvladus/Errands/releases/tag/45.1.6)

**Comment by wada3n** [comment]
Hi @mrvladus,
in Due, The calendar pop-up in the Details view still isn't scrollable!

![Screenshot from 2024-02-08 22-08-08](https://github.com/mrvladus/Errands/assets/13304792/accaea2f-aca5-42c4-a2e1-89897e16ebf3)

**Comment by mrvladus** [comment]
Fixed in bc03da7. Sorry, missed that :)
