### ISSUE TITLE
Tags not synchronizing correctly

### ISSUE THREAD

**Issue by CristianKerr** [mrvladus/Errands#247]
Hi, I started using Errands on my desktop, in my phone I have Tasks.org and I noticed when I change tags in Errands, the changes doesn't show in Tasks.org. I have checked the changes and I noticed that in CalDav there are more categories parameters like e.g.:
```
CATEGORIES:tag1
CATEGORIES:tag2
```
but it should be:
`CATEGORIES:tag1,tag2` right? At least this is what I see when I check what comes out of Tasks.org.

When I try to actually create a new task in Errands and I add more than one tag, I see only the first one e.g.:
`CATEGORIES:tag1`

its possible that Errands ignore the CATEGORIES parameter if its not in particular place in the message, and there is probably issue with collecting all the tags in one parameter as well (the rest being omitted).

**Comment by mrvladus** [comment]
Yeah, can confirm this. I'll look into it now.

**Comment by mrvladus** [comment]
Okay, it was only one line. Fixed in f0531ead327eeeda9f1be181adb52f16bebc2fdc. I'll create a release with fix.

**Comment by CristianKerr** [comment]
wow you are super fast, thanks a lot!

**Comment by mrvladus** [comment]
I've pushed update on flathub, don't know how long it will take the update to arrive, probably several hours. Thanks for report!

**Comment by CristianKerr** [comment]
Hi @mrvladus it still happens. I have the latest version I tried to create new task. First I gave it only 1 tag and synchronized. Then I added second and synchronized and it is split again, there is CATEGORIES twice again. 
I wonder if I have issue installing the new version though? My flatpak manager shows I have the latest, but when I click on "About" in the app I see 46.0 (not 46.0.1) any chance you didn't update the version in about? Thanks!

**Comment by mrvladus** [comment]
I've made a typo in version number. New version is 46.0ю1 :)

**Comment by CristianKerr** [comment]
Cool, now I see this, maybe some cache or something. Anyway now the categories are in one CATEGORIES. Interesting is that it still doesn't show in Tasks.org (but that is probably their bug now, unless there is something about ordering the properties.. Thanks a lot.

**Comment by mrvladus** [comment]
Flathub is just taking too long to push updates for some reason.

**Comment by CristianKerr** [comment]
If you are curious I added the bug to Tasks.org here: https://github.com/tasks/tasks/issues/2868
I attached there full message in order to see if order play some role. :smile:
