### ISSUE TITLE
App suddenly deletes all tasks, cannot add any new ones

### ISSUE THREAD

**Issue by turtlegarden** [mrvladus/Errands#68]
Version: 45.0

When I updated to 45.0, I suddenly found that all of my tasks were completely gone and that keyboard shortcuts did not work. Pressing Enter does not even work to create a new task, as shown in the attached video:

[Skärminspelning från 2023-10-17 21-48-50.webm](https://github.com/mrvladus/Errands/assets/52264162/a0784816-caed-4fd4-9348-1b3207eeb016)

**Comment by mrvladus** [comment]
There is tasks backup at $HOME/.var/app/io.github.mrvladus.List/data/data.old.json
Copy it somewhere and launch app in terminal, paste otput here

**Comment by niktss** [comment]
I'm experiencing this issue as well. Data.json seems unaffected, but tasks are gone, and can't add new ones.

- log.txt in /.var/app

```[DEBUG] Starting Errands 45.0
[DEBUG] Initialize GSettings
[DEBUG] Initialize sync provider
[INFO] Sync disabled
[DEBUG] Loading tasks
[ERROR] Data file is corrupted. Creating backup at /home/ursustheodoricus/.var/app/io.github.mrvladus.List/data/list/data.old.json
```

- terminal log
```
[DEBUG] Starting Errands 45.0
[DEBUG] Initialize GSettings
[DEBUG] Initialize sync provider
[INFO] Sync disabled
[DEBUG] Loading tasks
[ERROR] Data file is corrupted. Creating backup at /home/ursustheodoricus/.var/app/io.github.mrvladus.List/data/list/data.old.json
Traceback (most recent call last):
  File "/app/share/errands/errands/utils.py", line 288, in get
    converted_data: UserDataDict = self.convert(self, data)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserData.convert() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/errands/errands/application.py", line 21, in do_activate
    win.perform_startup()
  File "/app/share/errands/errands/window.py", line 72, in perform_startup
    self._load_tasks()
  File "/app/share/errands/errands/window.py", line 218, in _load_tasks
    for task in UserData.get()["tasks"]:
                ^^^^^^^^^^^^^^
  File "/app/share/errands/errands/utils.py", line 298, in get
    self.create_copy(self)
TypeError: UserData.create_copy() takes 1 positional argument but 2 were given
[ERROR] Data file is corrupted. Creating backup at /home/ursustheodoricus/.var/app/io.github.mrvladus.List/data/list/data.old.json
Traceback (most recent call last):
  File "/app/share/errands/errands/utils.py", line 288, in get
    converted_data: UserDataDict = self.convert(self, data)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserData.convert() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/errands/errands/window.py", line 397, in on_task_added
    new_data: UserDataDict = UserData.get()
                             ^^^^^^^^^^^^^^
  File "/app/share/errands/errands/utils.py", line 298, in get
    self.create_copy(self)
TypeError: UserData.create_copy() takes 1 positional argument but 2 were given
```

**Comment by niktss** [comment]
@turtlegarden as an immediate workaround, you can rollback to the previous version - I didn't experience issues, but backup your data.json just in case:
```
sudo flatpak update --commit=a470a4f465440316c996232340944f5f322ab4a956a23951887abab0cc4fe1d6 io.github.mrvladus.List
```

**Comment by mrvladus** [comment]
Fixed in the latest release. Thank you for reporting! Update on flathub in a couple hours

**Comment by mrvladus** [comment]
It was just the UI bug, tasks should be fine

**Comment by turtlegarden** [comment]
I compiled the previous version and all my tasks are still present! I will try the new Flathub update soon, thank you for your quick response!
